# Generated by Django 4.0.4 on 2022-04-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('body_type', models.CharField(max_length=255, verbose_name='Тип кузова')),
                ('engine_type', models.CharField(max_length=255, verbose_name='Тип двигателя')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет кузова')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('description', models.TextField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.category')),
            ],
        ),
    ]
